FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json tsconfig.json ./
RUN npm install

COPY src/ ./src
COPY tailwind.config.js ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

COPY package.json ./
RUN npm install --only=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
ENV NODE_ENV=production

CMD ["npm", "start"]
